# Generated by Django 3.1.13 on 2021-08-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('keke', 'Keke'), ('taxi', 'Taxi'), ('Luxury Cab', 'Luxury Cab')], default='keke', max_length=150)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('black', 'Black'), ('Silver', 'Silver'), ('yellow', 'Yellow')], default='red', max_length=20)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('engine_no', models.PositiveBigIntegerField(unique=True)),
                ('plate_no', models.CharField(max_length=10, unique=True)),
                ('tracker_imei_no', models.IntegerField(unique=True)),
                ('vehicle_papers', models.ImageField(upload_to='vehicle_papers')),
                ('inspection', models.CharField(choices=[('good', 'In Good Shape'), ('bad', 'Needs Repairs'), ('repaired', 'Have been Repaired')], default='good', max_length=25)),
                ('inspection_description', models.TextField(max_length=500)),
                ('value_at_acquisition', models.IntegerField()),
                ('interest_amount', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('not hired', 'Not Yet Hired'), ('hired', 'Hired'), ('completed', 'completed')], max_length=50)),
                ('weekly_returns', models.IntegerField()),
                ('paid_so_far', models.IntegerField()),
                ('left_to_pay', models.IntegerField()),
                ('tenure_duration', models.DurationField()),
                ('hired_date', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicletype')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='InvestorVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Investor', to='investor.investor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VehiclesInvested', to='vehicle.vehicleinfo')),
            ],
            options={
                'unique_together': {('investor', 'vehicle')},
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Driver', to='driver.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DriverAssignedVehicle', to='vehicle.vehicleinfo')),
            ],
            options={
                'unique_together': {('driver', 'vehicle')},
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('payed', 'Payed'), ('due', 'Due'), ('not payed', 'Not Payed'), ('completed', 'Completed')], max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_accounting', to='vehicle.drivervehicle')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_accounting', to='vehicle.investorvehicle')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
